services:
  https-proxy:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    networks:
      - proxy
    restart: no
    environment:
      DOMAINS: 'retriever.com -> http://retriever:80'
      STAGE: 'local' # Don't use production until staging works
      ERROR_LOG: default
      ACCESS_LOG: default
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

  retriever:
    # image: retriever
    build:
      context: .
      dockerfile: simple_fastapi.Dockerfile
    networks:
      - db
      - proxy
    volumes:
      - type: bind
        source: ${API_PATH}
        target: /retriever
        read_only: true
    command:
      [
        "uvicorn",
        "retriever.hello_world_api:app",
        "--proxy-headers",
        "--host",
        "0.0.0.0",
        "--port",
        "80"
      ]

  database:
    build:
      context: .
      dockerfile: chroma.Dockerfile
    networks:
      - db
    volumes:
      - type: bind
        source: ${DB_DATA_PATH}
        target: /chroma/chroma
        read_only: true
    command:
      [
        "chroma",
        "run",
        "--path",
        "/chroma/chroma",
        "--host",
        "database",
        "--port",
        "8000"
      ]

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '<a secure password>'
    networks:
      - db

  phobos:
    container_name: phobos
    build: chroma.Dockerfile
    command: sleep infinity
    networks:
      - db
      - proxy

networks:
  db:
    driver: bridge
  proxy:


volumes:
  https-portal-data:
