services:
  https-proxy:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    networks:
      - proxy
    restart: no
    environment:
      DOMAINS: 'retriever.com -> http://retriever:8000'
      STAGE: 'local' # Don't use production until staging works
      # FORCE_RENEW: 'true'

  retriever:
    image: retriever
    build:
      context: .
      dockerfile: ./retriever_base.Dockerfile
    networks:
      - db
      - proxy

  phobos:
    container_name: phobos
    image: busybox
    command: sleep infinity
    networks:
      - db
      - proxy

networks:
  db:
    driver: bridge
  proxy:


volumes:
  chroma-logs:
