services:
  streamlit:
    ports:
      - 8501:8501
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    command:
      ["streamlit", "run","--server.headless","true", "--server.address", "0.0.0.0", "--server.port", "8501", "/src/streamlit/app.py"]
      # sleep infinity
